#!/bin/bash

# build site with jekyll, by default to `_site' folder
bundle exec jekyll build

# initialize new repo from newly built _site folder
cd /home/travis/build/the-engine-room/2017-retro/_site
git init
git config user.email "${GH_EMAIL}"
git config user.name "${GH_USERNAME}"
git remote add upstream https://${GH_USERNAME}:${GH_TOKEN}@${GH_REF}
git fetch upstream
git reset upstream/gh-pages
touch .nojekyll

# add, commit and push changes to master
git add -A .
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
git push --force "https://${GH_USERNAME}:${GH_TOKEN}@${GH_REF}" master:master > /dev/null 2>&1
